# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: Build
  steps:

  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - task: Maven@4

    inputs:
      mavenPomFile: './complete/pom.xml'
      goals: 'clean install'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false


  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: './complete/target'
      artifact: 'java-app'
      publishLocation: 'pipeline'

- job: Deploy
  steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'current'
      artifactName: 'java-app'
      itemPattern: '*.jar'
      targetPath: '$(Pipeline.Workspace)'


